name: orchestrator

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  deploy-dev:
    # secrets: inherit
    uses: croesusfin/pipeline-poc/.github/workflows/reuse.yml@main
    with:
      environment: dev
  
  deploy-prod:    
    uses: croesusfin/pipeline-poc/.github/workflows/reuse.yml@main
    # secrets: inherit
    with:
      environment: prod
