# This is a basic workflow to help you get started with Actions

name: reuseable-workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      thesecret:
        required: true

jobs:
  deploy:    
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Set as env var
        run: echo "thesecretis=${{ secrets.thesecret }}" >> $GITHUB_ENV
      - name: Use the value
        run: echo ${{ env.thesecretis }}
