# This is a basic workflow to help you get started with Actions

name: reuseable-workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      thesecret:
        required: true

jobs:
  deploy:    
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ secrets.thesecret }}
